### ISSUE TITLE
Mauvaise instanciation Entity

### ISSUE THREAD

**Issue by nounoursheureux** [whitedrop/whitedrop#4]
Dans la fonction `spawnEntity` du fichier Whitedrop.cpp tu crées un objet Entity comme ça:
```
Entity ent = Entity(std::string,std::string,Ogre::Vector3,Ogre::Vector3,std::string)
```
Alors que le constructeur d'Entity est différent: 
```
Entity::Entity(std::string,Ogre::Vector3,Ogre::Vector3,ObjectData*,Chunk*)
```
Donc ça ne compile pas :)

**Comment by vinz243** [comment]
En effet j'aurais du faire une branche mais maintenant c'est trop tard :)
Mais je suis justement entrain de corriger ça

**Comment by nounoursheureux** [comment]
Ah d'accord :+1: . En effet je te conseille de créer une branche *unstable* ou quelque chose comme ça pour le code en développement (voire même de pas commiter quelque chose qui marche pas :p )

**Comment by vinz243** [comment]
Voilà j'ai créer une nouvelle branche `feature/lod`et j'ai fait un reset juste avant le premier commit qui introduisait des erreurs. Puis un cherry-pick de tes commits. Normalement c'est bon :)
